// ═══════════════════════════════════════════════════════════════
// Pattern: EF Migration Designer file — auto-generated companion.
// Contains: migration metadata, snapshot of the model at migration time.
// Do NOT manually edit — this file is created by 'dotnet ef migrations add'.
// ═══════════════════════════════════════════════════════════════

// <auto-generated />
using System;
using Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable enable

namespace Infrastructure.Migrations;

[DbContext(typeof(TaskFlowDbContextTrxn))]
[Migration("20260101000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        // Pattern: Model snapshot captured at migration creation time.
        // Subsequent migrations compare against this snapshot to generate delta SQL.
        // Full model definition omitted for brevity — see TaskFlowDbContextTrxnModelSnapshot.cs.
#pragma warning restore 612, 618
    }
}
