// ═══════════════════════════════════════════════════════════════
// Pattern: EF Core Migration — InitialCreate.
// Generated by: dotnet ef migrations add InitialCreate
// This file is COMMITTED to source control and applied at startup
// (if RunStartupEFMigrations is true) or manually via dotnet ef database update.
//
// Migration conventions:
// - File naming: {Timestamp}_{MigrationName}.cs
// - Timestamp format: yyyyMMddHHmmss (UTC)
// - Migration names: PascalCase, descriptive (InitialCreate, AddCategoryEntity, etc.)
// - Always include .Designer.cs and ModelSnapshot alongside.
// ═══════════════════════════════════════════════════════════════

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable enable

namespace Infrastructure.Migrations;

/// <summary>
/// Pattern: Initial migration — creates all tables for the TodoItem domain.
/// Demonstrates:
/// - Tenant-scoped clustered indexes
/// - Non-clustered primary keys
/// - Owned value objects (DateRange → inline columns)
/// - Self-referencing hierarchies (TodoItem.ParentId)
/// - Enum columns with defaults
/// - Cascade vs Restrict delete behaviors
/// - Named indexes with TenantId leading column
/// </summary>
public partial class InitialCreate : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // ── Category ──
        // Pattern: Simple entity with non-clustered PK + clustered (TenantId, Id).
        migrationBuilder.CreateTable(
            name: "Category",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                IsActive = table.Column<bool>(type: "bit", nullable: false, defaultValue: true),
                CreatedBy = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                CreatedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                UpdatedBy = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                UpdatedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true)
            },
            constraints: table =>
            {
                // Pattern: PK is NOT clustered — physical order is on (TenantId, Id).
                table.PrimaryKey("PK_Category", x => x.Id)
                    .Annotation("SqlServer:Clustered", false);
            });

        // Pattern: Clustered composite index — physical disk sort order.
        migrationBuilder.CreateIndex(
            name: "CIX_Category_TenantId_Id",
            table: "Category",
            columns: new[] { "TenantId", "Id" },
            unique: true)
            .Annotation("SqlServer:Clustered", true);

        // ── Tag ──
        migrationBuilder.CreateTable(
            name: "Tag",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                Name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                ColorHex = table.Column<string>(type: "nvarchar(7)", maxLength: 7, nullable: true),
                CreatedBy = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                CreatedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                UpdatedBy = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                UpdatedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Tag", x => x.Id);
            });

        // Pattern: Unique index on Tag.Name — tags are global, no tenant partition.
        migrationBuilder.CreateIndex(
            name: "IX_Tag_Name",
            table: "Tag",
            column: "Name",
            unique: true);

        // ── TodoItem ──
        // Pattern: Rich entity with self-referencing hierarchy, owned type, and multiple FKs.
        migrationBuilder.CreateTable(
            name: "TodoItem",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                Title = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                Description = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true),
                Status = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                Priority = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                CategoryId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                AssignedToId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                ParentId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                // Pattern: Owned value object — stored as inline columns, not a separate table.
                DateRange_StartDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                DateRange_EndDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                CompletedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                CreatedBy = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                CreatedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                UpdatedBy = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                UpdatedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_TodoItem", x => x.Id)
                    .Annotation("SqlServer:Clustered", false);

                // Pattern: Self-referencing FK — Restrict prevents orphaned sub-tasks.
                table.ForeignKey(
                    name: "FK_TodoItem_TodoItem_ParentId",
                    column: x => x.ParentId,
                    principalTable: "TodoItem",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);

                // Pattern: Restrict on category FK — can't delete Category while TodoItems reference it.
                table.ForeignKey(
                    name: "FK_TodoItem_Category_CategoryId",
                    column: x => x.CategoryId,
                    principalTable: "Category",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
            });

        // Pattern: Clustered composite on (TenantId, Id) for tenant-scoped queries.
        migrationBuilder.CreateIndex(
            name: "CIX_TodoItem_TenantId_Id",
            table: "TodoItem",
            columns: new[] { "TenantId", "Id" },
            unique: true)
            .Annotation("SqlServer:Clustered", true);

        // Pattern: Non-clustered indexes — TenantId always leads for tenant isolation.
        migrationBuilder.CreateIndex(
            name: "IX_TodoItem_TenantId_Status",
            table: "TodoItem",
            columns: new[] { "TenantId", "Status" });

        migrationBuilder.CreateIndex(
            name: "IX_TodoItem_TenantId_CategoryId",
            table: "TodoItem",
            columns: new[] { "TenantId", "CategoryId" });

        migrationBuilder.CreateIndex(
            name: "IX_TodoItem_ParentId",
            table: "TodoItem",
            column: "ParentId");

        // ── Comment (child of TodoItem) ──
        migrationBuilder.CreateTable(
            name: "Comment",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                TodoItemId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                Text = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                AuthorId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                CreatedBy = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                CreatedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                UpdatedBy = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                UpdatedDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Comment", x => x.Id);
                // Pattern: Cascade — deleting a TodoItem deletes its Comments.
                table.ForeignKey(
                    name: "FK_Comment_TodoItem_TodoItemId",
                    column: x => x.TodoItemId,
                    principalTable: "TodoItem",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_Comment_TodoItemId",
            table: "Comment",
            column: "TodoItemId");

        // ── TodoItemTag (junction table) ──
        // Pattern: Many-to-many — explicit junction entity with composite PK.
        migrationBuilder.CreateTable(
            name: "TodoItemTag",
            columns: table => new
            {
                TodoItemId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                TagId = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_TodoItemTag", x => new { x.TodoItemId, x.TagId });
                table.ForeignKey(
                    name: "FK_TodoItemTag_TodoItem_TodoItemId",
                    column: x => x.TodoItemId,
                    principalTable: "TodoItem",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "FK_TodoItemTag_Tag_TagId",
                    column: x => x.TagId,
                    principalTable: "Tag",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_TodoItemTag_TagId",
            table: "TodoItemTag",
            column: "TagId");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Pattern: Down drops tables in reverse dependency order.
        migrationBuilder.DropTable(name: "TodoItemTag");
        migrationBuilder.DropTable(name: "Comment");
        migrationBuilder.DropTable(name: "TodoItem");
        migrationBuilder.DropTable(name: "Tag");
        migrationBuilder.DropTable(name: "Category");
    }
}
