// ═══════════════════════════════════════════════════════════════
// Pattern: EF Core Model Snapshot — generated by 'dotnet ef migrations add'.
// The runtime uses this to determine what change(s) the NEXT migration must apply.
// Always kept in sync with the latest migration — never manually edited.
// Located alongside migration files in the Migrations/ folder.
// ═══════════════════════════════════════════════════════════════

// <auto-generated />
using System;
using Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable enable

namespace Infrastructure.Migrations;

[DbContext(typeof(TaskFlowDbContextTrxn))]
partial class TaskFlowDbContextTrxnModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        // Pattern: Snapshot contains the complete model definition.
        // Simplified here to show the pattern — real snapshots include
        // every entity, property, relationship, and index.
        //
        // Key conventions shown in the InitialCreate migration:
        // - Non-clustered PK with clustered (TenantId, Id) composite
        // - Owned value objects mapped to inline columns
        // - Self-referencing FK with Restrict delete
        // - Junction table with composite PK
        // - Named indexes with TenantId leading column
        //
        // To regenerate: dotnet ef migrations add <Name> -p Infrastructure -s TaskFlow.Api
#pragma warning restore 612, 618
    }
}
